import React, { useCallback, useState } from 'react';
import { View, Text, FlatList, Pressable, StyleSheet, Alert } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import MedicationCard from '../components/MedicationCard';
import { listarMedicamentos, removerMedicamento, contarTomadasPorStatus } from '../db/database';
import { cancelarAlarmesDoMedicamento } from '../services/notifications';
import { listarCuidadores } from '../services/sync';
import { BannerAd, BannerAdSize, BANNER_ID } from '../services/ads';
import { Medicamento, CuidadorVinculado } from '../types';

function proximoHorarioTexto(m: Medicamento): string { const agora=new Date(); const atual=agora.getHours()*60+agora.getMinutes(); const mins=m.horarios.map(h=>{const [hh,mm]=h.split(':').map(Number);return hh*60+mm}).sort((a,b)=>a-b); const p=mins.find(x=>x>=atual)??mins[0]; return `${String(Math.floor(p/60)).padStart(2,'0')}:${String(p%60).padStart(2,'0')}`; }

export default function HomeScreen({ navigation }: any) {
  const [medicamentos,setMedicamentos]=useState<Medicamento[]>([]); const [resumo,setResumo]=useState({tomado:0,perdido:0,adiado:0}); const [cuidadores,setCuidadores]=useState<CuidadorVinculado[]>([]);
  useFocusEffect(useCallback(()=>{setMedicamentos(listarMedicamentos());const stats=contarTomadasPorStatus();setResumo({tomado:stats.tomado||0,perdido:stats.perdido||0,adiado:stats.adiado||0});listarCuidadores().then(setCuidadores);},[]));
  function confirmarExclusao(m:Medicamento){Alert.alert('Remover remédio',`Deseja parar os lembretes de "${m.nome}"?`,[{text:'Cancelar',style:'cancel'},{text:'Remover',style:'destructive',onPress:async()=>{removerMedicamento(m.id);await cancelarAlarmesDoMedicamento(m.id);setMedicamentos(listarMedicamentos());}}]);}
  const total=resumo.tomado+resumo.perdido+resumo.adiado; const taxa=total>0?Math.round(resumo.tomado/total*100):0;
  return <View style={styles.container}>
    <Text style={styles.titulo}>Meus Remédios</Text>
    {cuidadores.length>0&&<Pressable style={styles.cuidadorCard} onPress={()=>navigation.navigate('VincularCuidador')}><Text style={styles.cuidadorTexto}>👨‍⚕️ {cuidadores.length} cuidador{cuidadores.length>1?'es':''} vinculado{cuidadores.length>1?'s':''}</Text><Text style={styles.cuidadorSub}>Toque para gerenciar →</Text></Pressable>}
    <Pressable style={styles.estoqueCard} onPress={()=>navigation.navigate('Estoque')}><Text style={styles.estoqueTitulo}>📦 Projeção de estoque</Text><Text style={styles.estoqueSub}>Veja quando seus medicamentos podem acabar e repõe antes.</Text></Pressable>
    <Pressable style={styles.resumoCard} onPress={()=>navigation.navigate('RelatorioAdesao')}><Text style={styles.resumoTitulo}>📊 Sua Adesão ao Tratamento</Text><View style={styles.resumoLinha}><View style={styles.resumoItem}><Text style={[styles.resumoNumero,{color:'#2ECC71'}]}>{resumo.tomado}</Text><Text style={styles.resumoLabel}>Tomados</Text></View><View style={styles.resumoItem}><Text style={[styles.resumoNumero,{color:'#F39C12'}]}>{resumo.adiado}</Text><Text style={styles.resumoLabel}>Adiados</Text></View><View style={styles.resumoItem}><Text style={[styles.resumoNumero,{color:'#E74C3C'}]}>{resumo.perdido}</Text><Text style={styles.resumoLabel}>Perdidos</Text></View><View style={styles.resumoItem}><Text style={[styles.resumoNumero,{color:'#1E3A5F'}]}>{taxa}%</Text><Text style={styles.resumoLabel}>Taxa</Text></View></View><Text style={styles.resumoDica}>Toque para ver relatório completo →</Text></Pressable>
    {medicamentos.length===0?<View style={styles.vazio}><Text style={styles.vazioTexto}>Nenhum remédio cadastrado ainda.\nToque no botão abaixo para começar.</Text></View>:<FlatList data={medicamentos} keyExtractor={m=>m.id} renderItem={({item})=><MedicationCard medicamento={item} proximoHorario={proximoHorarioTexto(item)} onPress={()=>navigation.navigate('AddMedicamento',{medicamento:item})} onExcluir={()=>confirmarExclusao(item)} onVerHistorico={()=>navigation.navigate('HistoricoMedicamento',{medicamentoId:item.id})}/>} contentContainerStyle={{paddingBottom:20}}/>}
    <Pressable style={styles.botaoAdicionar} onPress={()=>navigation.navigate('AddMedicamento')}><Text style={styles.botaoAdicionarTexto}>+ Adicionar Remédio</Text></Pressable>
    <View style={styles.bannerContainer}><BannerAd unitId={BANNER_ID} size={BannerAdSize.ANCHORED_ADAPTIVE_BANNER}/></View>
  </View>;
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#F4F7FB',padding:20},titulo:{fontSize:30,fontWeight:'900',color:'#1E3A5F',marginBottom:12,marginTop:10},cuidadorCard:{backgroundColor:'#118AB2',borderRadius:14,padding:14,marginBottom:12},cuidadorTexto:{fontSize:16,fontWeight:'700',color:'#FFF'},cuidadorSub:{fontSize:13,color:'#DCE6F2',marginTop:2},estoqueCard:{backgroundColor:'#EAF7F1',borderRadius:16,padding:15,marginBottom:12,borderWidth:1,borderColor:'#B7E4CD'},estoqueTitulo:{fontSize:18,fontWeight:'900',color:'#176B4D'},estoqueSub:{fontSize:14,color:'#46675A',marginTop:4,lineHeight:20},resumoCard:{backgroundColor:'#FFF',borderRadius:18,padding:16,marginBottom:14,elevation:2},resumoTitulo:{fontSize:16,fontWeight:'700',color:'#1E3A5F',marginBottom:10},resumoLinha:{flexDirection:'row',justifyContent:'space-around'},resumoItem:{alignItems:'center'},resumoNumero:{fontSize:22,fontWeight:'800'},resumoLabel:{fontSize:12,color:'#5B6B7C',marginTop:2},resumoDica:{fontSize:12,color:'#118AB2',marginTop:10,textAlign:'center'},vazio:{flex:1,alignItems:'center',justifyContent:'center'},vazioTexto:{fontSize:18,color:'#5B6B7C',textAlign:'center',lineHeight:26},botaoAdicionar:{backgroundColor:'#1E3A5F',paddingVertical:18,borderRadius:18,alignItems:'center',marginBottom:10},botaoAdicionarTexto:{color:'#FFF',fontSize:20,fontWeight:'800'},bannerContainer:{alignItems:'center'}});
