import * as SQLite from 'expo-sqlite';
import { Medicamento, Tomada } from '../types';
const db = SQLite.openDatabaseSync('medalerta.db');
function ensureSchema(){
  const cols=db.getAllSync('PRAGMA table_info(medicamentos)') as any[];
  const add=(name:string,type:string)=>{if(!cols.some(c=>c.name===name))db.execSync(`ALTER TABLE medicamentos ADD COLUMN ${name} ${type}`)};
  add('unidadeEstoque',"TEXT DEFAULT 'unidades'"); add('quantidadePorDose','REAL DEFAULT 1'); add('estoqueMinimo','REAL DEFAULT 0'); add('observacoes','TEXT');
  const tomadaCols=db.getAllSync('PRAGMA table_info(tomadas)') as any[]; if(!tomadaCols.some(c=>c.name==='quantidadeConsumida'))db.execSync('ALTER TABLE tomadas ADD COLUMN quantidadeConsumida REAL DEFAULT 1');
}
export function iniciarBanco(){db.execSync(`CREATE TABLE IF NOT EXISTS medicamentos(id TEXT PRIMARY KEY NOT NULL,nome TEXT NOT NULL,dosagem TEXT,fotoUri TEXT,horarios TEXT NOT NULL,dataInicio TEXT NOT NULL,totalDias INTEGER NOT NULL,cor TEXT NOT NULL,ativo INTEGER NOT NULL DEFAULT 1,estoque REAL);CREATE TABLE IF NOT EXISTS tomadas(id TEXT PRIMARY KEY NOT NULL,medicamentoId TEXT NOT NULL,horarioPrevisto TEXT NOT NULL,horarioReal TEXT,status TEXT NOT NULL DEFAULT 'pendente',quantidadeConsumida REAL DEFAULT 1,FOREIGN KEY (medicamentoId) REFERENCES medicamentos(id));CREATE INDEX IF NOT EXISTS idx_tomadas_medicamento ON tomadas(medicamentoId);CREATE INDEX IF NOT EXISTS idx_tomadas_status ON tomadas(status);`);ensureSchema();}
function rowToMedicamento(r:any):Medicamento{return{id:r.id,nome:r.nome,dosagem:r.dosagem||'',fotoUri:r.fotoUri,horarios:JSON.parse(r.horarios),dataInicio:r.dataInicio,totalDias:r.totalDias,cor:r.cor,ativo:!!r.ativo,estoque:r.estoque==null?undefined:Number(r.estoque),unidadeEstoque:r.unidadeEstoque||'unidades',quantidadePorDose:Number(r.quantidadePorDose||1),estoqueMinimo:Number(r.estoqueMinimo||0),observacoes:r.observacoes||undefined};}
export function salvarMedicamento(m:Medicamento){ensureSchema();db.runSync(`INSERT OR REPLACE INTO medicamentos(id,nome,dosagem,fotoUri,horarios,dataInicio,totalDias,cor,ativo,estoque,unidadeEstoque,quantidadePorDose,estoqueMinimo,observacoes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[m.id,m.nome,m.dosagem,m.fotoUri,JSON.stringify(m.horarios),m.dataInicio,m.totalDias,m.cor,m.ativo?1:0,m.estoque??null,m.unidadeEstoque||'unidades',Math.max(.01,Number(m.quantidadePorDose)||1),Math.max(0,Number(m.estoqueMinimo)||0,m.observacoes||null]);}
export function listarMedicamentos():Medicamento[]{ensureSchema();return(db.getAllSync('SELECT * FROM medicamentos WHERE ativo=1 ORDER BY nome COLLATE NOCASE') as any[]).map(rowToMedicamento);}
export function buscarMedicamentoPorId(id:string):Medicamento|null{ensureSchema();const rows=db.getAllSync('SELECT * FROM medicamentos WHERE id=? AND ativo=1',[id]) as any[];return rows.length?rowToMedicamento(rows[0]):null;}
export function removerMedicamento(id:string){db.runSync('UPDATE medicamentos SET ativo=0 WHERE id=?',[id]);}
export function registrarTomada(t:Tomada){ensureSchema();db.runSync('INSERT OR REPLACE INTO tomadas(id,medicamentoId,horarioPrevisto,horarioReal,status,quantidadeConsumida) VALUES(?,?,?,?,?,?)',[t.id,t.medicamentoId,t.horarioPrevisto,t.horarioReal,t.status,t.quantidadeConsumida??1]);}
export function historicoDoMedicamento(medicamentoId:string):Tomada[]{ensureSchema();return db.getAllSync('SELECT * FROM tomadas WHERE medicamentoId=? ORDER BY horarioPrevisto DESC',[medicamentoId]) as Tomada[];}
export function listarTodasTomadas():Tomada[]{ensureSchema();return db.getAllSync('SELECT t.*,m.nome as medicamentoNome FROM tomadas t JOIN medicamentos m ON t.medicamentoId=m.id ORDER BY t.horarioPrevisto DESC') as Tomada[];}
export function contarTomadasPorStatus(medicamentoId?:string):Record<string,number>{ensureSchema();let q='SELECT status,COUNT(*) total FROM tomadas';const p:any[]=[];if(medicamentoId){q+=' WHERE medicamentoId=?';p.push(medicamentoId)}q+=' GROUP BY status';const rows=db.getAllSync(q,p) as any[];const r:Record<string,number>={pendente:0,tomado:0,adiado:0,perdido:0};for(const x of rows)r[x.status]=x.total;return r;}
export function marcarTomadasPerdidas(){ensureSchema();const limite=new Date(Date.now()-30*60*1000);db.runSync(`UPDATE tomadas SET status='perdido' WHERE status='pendente' AND horarioPrevisto<?`,[limite.toISOString()]);}
export function decrementarEstoque(medicamentoId:string,quantidade=1):number|null{ensureSchema();const q=Math.max(0,Number(quantidade)||0);db.runSync('UPDATE medicamentos SET estoque=MAX(0,COALESCE(estoque,0)-?) WHERE id=? AND estoque IS NOT NULL',[q,medicamentoId]);const rows=db.getAllSync('SELECT estoque FROM medicamentos WHERE id=?',[medicamentoId]) as any[];return rows.length&&rows[0].estoque!=null?Number(rows[0].estoque):null;}
